- name: variables to print
  hosts: web
  vars:
    NAME: narendra
    COURSE: "aws devops"
  tasks:
  - name: print the message
    ansible.builtin.debug:
      msg: "Hi, this is {{NAME}}, learing {{COURSE}}"

