- name: variables from prompt
  hosts: web
  vars_prompt:
  - name: COURSE
    prompt: please enther the course name
    private: false # not confidential
  - name: NAME
    prompt: please enther the name
    private: false # not confidential 
  tasks:
  - name: print the course information 
    ansible.builtin.debug:
      msg:  "Hi, this is {{NAME}}, learing {{COURSE}}"