- name: devops course information
  hosts: local
  vars:
    course: aws with devops # string 
    duration: 120 # number
    topics: # list
    - linux
    - k8s
    - ansible
    - terraform
    - docker
    - aws
    live: true # boolean
    tools: #map/dictionary
      ci: jenkins #string
      cm: ansible #string
      cloud: aws  #string
  tasks:
  - name: print the course information
    ansible.builtin.debug:
    msg: "hi, i am learing {{course}}, with duration: {{duration}}, topics are: {{topics}} and live: {{live}}, tools are: {{tools}} "



