- name: create a user
  hosts: web
  become: yes
  tasks:
  - name: check if user exists or not
    ansible.builtin.command: id expense
    register: USER # user ia a varibale that gets output for above command
    ignore_errors: true

  - name: print the user information
    ansible.builtin.debug:
      msg: "user info: {{USER}}"


  - name: craete a user
    ansible.builtin.command: id expense
    when: USER.rc != 0