- name: loops demo
  hosts: local
  connection: local
  tasks:
  - name: print the names
    ansible.builtin.debig:
      msg: "hello {{item}}"
    loop:
    - narendra
    - roger
    - nadal
    - sinner
