- name: loops demo
  hosts: web
  become: yes
  tasks:
  - name: install the packages
    ansible.builtin.package:
      name: "{{item}}"
      state: present
    loop:
    - mysql
    - nginx
    - httpd
    - postfix
