- name: demo for filters/functions
  hosts: local
  connection: local
  tasks:
  - name: print the default variables
    ansible.builtin.debug:
      msg: "hello {{ course | default('ansible') }} "

  - name: convert to upper case
    vars:
      greeting: "hello narendra"
    ansible.builtin.debug:
      msg: "{{ greeting | upper }}"

  - name: convert to lower case
    vars:
      greeting: "hello narendra"
    ansible.builtin.debug:
      msg: "{{ greeting | lower }}"

  - name: convert to lower case
    vars:
      numbers: [1,2,3,10,1,2]
    ansible.builtin.debug:
      msg: "{{ numbers | unique }}"

