- name: create ec2 instance & R53 records
  hosts: local
  connection: local
  vars:
    subnet_id: subnet-0070694a8aaf8ac25
    sg_id: sg-02a594d7aa82fa5df
    ami_id: ami-09c813fb71547fc4f
    instances:
    - frontend
    - backend
    - mysql
    zone: devops.online
  tasks:
  - name: ec2 instance creation
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      vpc_subnet_id: "{{ subnet_id }}"
      instance_type: "t3.micro"
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
    loop: "{{ instances }}"
    register: ec2_instances

  - name: print the output
    ansible.builtin.debug:
       msg: "{{ ec2_instances }}"
    #c create R53 private records
  - name: create R53 private records
    amazon.aws.route53:
      state: present
      zone: "{{ zone }}"
      record: "{{ item.item}}.{{ zone }}"
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}"
      wait: true
      overwrite: true

    loop: "{{ ec2_instances.results }}"

#c create R53 publc records for frontend
  - name: create R53 public records
    amazon.aws.route53:
      state: present
      zone: "{{ zone }}"
      record: "{{ zone }}"
      type: A
      ttl: 1
      value: "{{ item.instances[0].public_ip_address }}"
      wait: true
      overwrite: true

    loop: "{{ ec2_instances.results }}"
    when: item.item == "frontend"



