- name: create ec2 instance & R53 records
  hosts: local
  connection: local
  vars:
    subnet_id: subnet-0070694a8aaf8ac25
    sg_id: sg-02a594d7aa82fa5df
    ami_id: ami-09c813fb71547fc4f
    instances:
    - frontend
    - backend
    - mysql
  tasks:
  - name: ec2 instance creation
    amazon.aws.ec2.instance:
      name: "{{ item }}"
      vpc_subnet_id: "{{ subnet_id }}"
      instance_type: "t3.micro"
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
    loop: "{{ instances }}"
    register: ec2_instances


